#!/usr/bin/env python3
"""Generate the SystemVerilog symbol-list header for the replay harness.

    python3 scripts/gen_symbols.py AAPL,MSFT,... > replay_symbols.svh

Emits a localparam unpacked array of 8-character, space-padded symbol names,
in the order given (index i == book_idx i == the symbol_idx the Python golden
model assigns for the same --symbols order), zero-filling unused slots. The
generated header is included inside tb/replay/replay_top.sv's module body.

Zero is the "unused slot" sentinel in rtl/book_router.sv's symbol filter, which
is why unused entries are 64'd0 rather than eight spaces.
"""

import sys

NUM_SYMBOLS = 16  # must match book_pkg::NUM_SYMBOLS


def main(argv):
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    symbols = [s.strip() for s in argv[1].split(",") if s.strip()]
    if len(symbols) > NUM_SYMBOLS:
        print(f"gen_symbols: {len(symbols)} symbols exceeds NUM_SYMBOLS={NUM_SYMBOLS}",
              file=sys.stderr)
        return 1
    for s in symbols:
        if len(s) > 8:
            print(f"gen_symbols: symbol {s!r} is longer than 8 characters", file=sys.stderr)
            return 1

    items = ", ".join(f'{i}: "{s:<8}"' for i, s in enumerate(symbols))
    print("// Generated by scripts/gen_symbols.py -- do not edit.")
    print(f"// Symbols (index == book_idx): {','.join(symbols)}")
    print("localparam logic [63:0] REPLAY_SYMBOLS [book_pkg::NUM_SYMBOLS] =")
    print(f"    '{{{items}, default: 64'd0}};")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
